config/routes.rb
require 'api_constraints'

Wds::Application.routes.draw do
  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions

      put "permissions", to: "permissions#set",
                         as: "set_permissions"
    end
  end
  resources :users
  resources :projects do
    resources :posts
  end
  root :to => "projects#index"
  get 'auth/:provider/callback', to: 'sessions#oath_create'
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy", as: "signout"

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :quotations
    end
  end

end

  

app/models/project.rb
class Project < ActiveRecord::Base

  validates :name, presence: true

  has_many :posts, dependent: :delete_all

  has_many :permissions, as: :thing

  scope :viewable_by, ->(user) do
    joins(:permissions).where(permissions: { action: "view", user_id: user.id })
  end

  #scope :self.for, ->(user) do
  def self.for(user)
    user.admin? ? Project.all : Project.viewable_by(user)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authorize_admin!, except: [:index, :show]
  before_action :require_signin!, only: [:index, :show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.for(current_user).load
    #@projects = Project.for(current_user).all
    #@projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    p params

    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."

      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:notice] =  "Project has been updated."
      redirect_to @project 
    else
      flash[:alert] = "Project has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    flash[:notice] = "Project has been destroyed."

    redirect_to projects_path
  end

  private
    def project_params
      params.require(:project).permit(:name, :description)
    end

  private
    def set_project
      # move to model 
      #@project = if current_user.admin?
      #  Project.find(params[:id])
      #else
      #  @project = Project.viewable_by(current_user).find(params[:id])
      #end

      @project = Project.for(current_user).find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking" +
                    " for could not be found."
      redirect_to projects_path
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %>
        prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<% admins_only do %>
  <%= link_to "New Project", new_project_path %>
<% end %>
<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

<p>&nbsp;</p>
<p>&nbsp;</p>

<% if Quotation.first %>
  Random thoughts: 
  <%  q = Quotation.limit(1).offset(rand(Quotation.count)).first %> 
  <p><%= q.passage %> - <%= q.author %></p>
<% end %>

app/views/projects/new.html.erb
<h2>New Project</h2>
<%= form_for(@project) do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %>
        prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<h2><%= @project.name %></h2>
<% admins_only do %>
  <%= link_to "Edit Project", edit_project_path(@project) %>
  <%= link_to "Delete Project", 
      project_path(@project),
      method: :delete,
      data: { confirm:
                "Are you sure you want to delete this project?"
            } %>
<% end %>
<% authorized?(:"create posts", @project) do %>
  <%= link_to "New Post", new_project_post_path(@project) %>
<% end %>
<ul id='posts'>
  <% @project.posts.each do |post| %>
    <li>
      #<%= post.id %> -
      <%= link_to post.title, [@project, post] %>
    </li>
  <% end %>
</ul>